/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package echoesoffate;

import echoesoffate.MainFrame;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author User
 */
public class AsherValeSplashScreen extends javax.swing.JPanel {

    /**
     * Creates new form AsherValeSplashScreen
     */
    
    private MainFrame frame;
    
    public AsherValeSplashScreen(MainFrame frame) {
        this.frame = frame;
        initComponents();
        btnContinue.addActionListener(e -> {
            playButtonClickSound();
            frame.showScreen("Login");
        }); 
    }
    
    private Clip clickClip;
    
    private void playButtonClickSound() {
        try {
            if (clickClip != null && clickClip.isRunning()) {
                clickClip.stop();
            }
            File soundFile = new File("src/echoesoffateassets/button_click.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundFile);
            clickClip = AudioSystem.getClip();
            clickClip.open(audioStream);
            clickClip.setFramePosition(0);
            clickClip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDialogue = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDialogue.setFont(new java.awt.Font("Lucida Fax", 0, 22)); // NOI18N
        lblDialogue.setForeground(new java.awt.Color(255, 255, 204));
        lblDialogue.setText("Press Anywhere to Continue...");
        add(lblDialogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 740, -1, -1));

        btnContinue.setBackground(new java.awt.Color(36, 43, 53, 100));
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setContentAreaFilled(false);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 960));

        lblBackground.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/echoesoffateassets/splash_screen.png"))); // NOI18N
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, 1600, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed

    }//GEN-LAST:event_btnContinueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDialogue;
    // End of variables declaration//GEN-END:variables
}
